packages/anu-vue/src/components/drawer/ADrawer.tsx, packages/anu-vue/src/components/drawer/index.ts, packages/anu-vue/src/components/index.ts, packages/anu-vue/src/presets/theme-default/index.ts, packages/anu-vue/src/scss/index.scss, packages/documentation/docs/.vitepress/config.js, packages/documentation/docs/demos/drawer/DemoDrawerAnchor.vue, packages/documentation/docs/demos/drawer/DemoDrawerBasic.vue, packages/documentation/docs/demos/drawer/DemoDrawerPersistent.vue, packages/documentation/docs/demos/drawer/DemoDrawerWidth.vue, packages/documentation/docs/guide/components/drawer.md
Added drawer component, using the Dialog as reference
=> feat(drawer): added drawer component

packages/anu-vue/src/components/select/ASelect.tsx
Based on issue #38  I fixed the blank selected value of the ASelect component
=> fix(select): With option slot selected item's label doesn't render

.eslintrc.js, packages/anu-vue/src/components/drawer/ADrawer.tsx, packages/anu-vue/src/presets/theme-default/index.ts, packages/anu-vue/src/scss/index.scss, packages/documentation/docs/demos/drawer/DemoDrawerAnchor.vue, packages/documentation/docs/guide/components/drawer.md
https://user-images.githubusercontent.com/73536160/194831622-15d58b64-7243-4c43-b125-53924e7d95d2.mov
=> feat(drawer): add `top` & `bottom` anchor

CONTRIBUTING.md
=> docs(contributing): how to add new page link in sidebar

packages/anu-vue/src/components/dialog/ADialog.tsx
=> fix(dialog): Using classes causes warning

packages/anu-vue/src/components/select/ASelect.tsx
…on already selected item.
fix #58
=> fix(select): close options on selected item click

packages/anu-vue/src/components/base-input/ABaseInput.tsx
...to work with light/dark themes
Fix #48
=> fix(base-input): add bg transparent to AInput child for dark mode

packages/anu-vue/src/components/table/ATable.tsx
As I was testing the `ATable` component, I have found a few errors.
These changes fixing:
* by re-ordering declarations no `eslint` suppression is needed
* `toRefs()` call resulted a warning logged in the console (`toRefs() expects a reactive object but received a plain one.`), as it is expecting a reactive argument
=> fix(table): fixed `toRefs()` warning

.github/workflows/check-build.yml, .github/workflows/test-report.yml, package.json, packages/anu-vue/package.json, packages/anu-vue/src/components/btn/ABtn.tsx, packages/anu-vue/test/ABtn.test.ts, packages/anu-vue/test/ATable.test.ts, packages/anu-vue/test/__snapshots__/ABtn.test.ts.snap, packages/anu-vue/test/__snapshots__/ATable.test.ts.snap, packages/anu-vue/tsconfig.json, packages/anu-vue/tsconfig.node.json, packages/anu-vue/vite.config.ts, pnpm-lock.yaml, tsconfig.json
This PR demonstrates how vitest could be utilized for unit tests.
BTW: during testing I have found that disabling `ABtn` does not prevent firing click events :-0, so I have fixed it.
I cannot really test it (the test-report YAML workflow is triggered only on the default branch), but I expect test reports like [these](https://github.com/peterbud/anu/actions/runs/3660704846/jobs/6188172135)
=> test: added basic test infrastructure

packages/anu-nuxt/playground/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> chore: fix nuxt playground @anu-vue/preset-theme-default

docs/guide/components/alert.md, docs/guide/components/badge.md, docs/guide/features/arbitrary-sizes.md, docs/guide/features/dx-focused.md, docs/guide/features/presets.md, docs/guide/features/theme.md, docs/guide/getting-started/customization.md, docs/guide/getting-started/index.md, docs/guide/getting-started/installation.md, docs/index.md, docs/ui/introduction.md
Fix documentation typos that are present in Anu's docs.
=> docs: fix typo

docs/components/demos/card/DemoCardVariants.vue, docs/guide/components/alert.md, docs/guide/components/avatar.md, docs/guide/components/badge.md, docs/guide/components/rating.md, docs/guide/components/switch.md
Minor fixes in docs.
- consistent dot at the end of lines
-  icon in alert instead of button
- variant in badge doesn't exist
- dot prop in badge
- Also removed strange `<p>Awesome</p>` in card variants.
=> docs: minor fixes & badge docs updates

packages/anu-nuxt/.nuxtrc, packages/anu-nuxt/package.json, packages/anu-nuxt/playground/nuxt.config.ts, packages/anu-nuxt/playground/unocss.config.ts, packages/anu-nuxt/src/module.ts, packages/anu-vue/src/index.ts, pnpm-lock.yaml
- Fixed: Types for components 
- Fixed: Dev playground to work within the mono repo 💯 
- Removed: `unocss.config.ts` within playground since `unocss` fixed it in later verisons
- Added: New module props `initialTheme` and `themes` to replicate what core does
- Added: 😍 Added to **Nuxt DevTools** if enabled
Made installation basically simply without no need for additional setup. Making it super easy to install and work with it!
Take a look it's nice
https://user-images.githubusercontent.com/6619884/221991742-d15b3414-07c9-4e4d-b652-5d051d3626a2.mov
Thanks,
CP 🚀
=> feat(anu-nuxt): improved nuxt module + nuxt DevTools support

packages/anu-vue/src/components/floating/AFloating.vue, packages/anu-vue/src/components/floating/index.ts, packages/anu-vue/src/components/floating/props.ts, packages/anu-vue/src/components/tooltip/ATooltip.vue, packages/anu-vue/src/components/tooltip/props.ts
=> fix(tooltip): middleware prop not working

packages/anu-vue/src/components/dialog/ADialog.vue, packages/anu-vue/src/components/drawer/ADrawer.vue
=> fix(drawer,dialog): handle persistent prop reactivity

.gitignore, packages/anu-vue/vite.config.ts
This PR also adds JetBrains stuff to gitignore.
=> test: remove optimize deps hack

docs/guide/features/presets.md, docs/guide/getting-started/grid.md
Not much really, just updated some links pointing to the new UnoCSS docs.
=> docs: updated links to unocss docs

package.json, packages/anu-vue/src/components/select/ASelect.vue, packages/anu-vue/test/ASelect.test.tsx, packages/anu-vue/test/setup.vitest.ts
=> fix(select): handle `null` & `undefined` as default values

packages/anu-vue/package.json
=> fix: package types

README.md
=> chore: adjust codesandbox link in README.md

packages/anu-nuxt/src/module.ts
=> fix: nuxt v3.7 remove compilerOptions.types
